#+TITLE:     emacs-hk-theme
#+AUTHOR:    Harikrishnan Gopalakrishnan
#+EMAIL:
#+DESCRIPTION: Modified dark version of emacs-leuven-theme
#+KEYWORDS:  emacs, leuven, custom theme, color theme, dark, popular, faces, melpa
#+LANGUAGE:  en

#+PROPERTY:  header-args :eval no

[[http://opensource.org/licenses/GPL-3.0][http://img.shields.io/:license-gpl-blue.svg]]

This is a customised version of https://github.com/fniessen/emacs-leuven-theme
See the original repository for details

* Original License

Copyright (C) 2003-2019 Free Software Foundation, Inc.

Author: Fabrice Niessen \\
Keywords: emacs color theme

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see http://www.gnu.org/licenses/.

[[http://opensource.org/licenses/GPL-3.0][http://img.shields.io/:license-gpl-blue.svg]]
